# Generated by Django 3.1.2 on 2020-10-17 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='img_link_storage',
            fields=[
                ('img_url', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('tweet_id', models.BigIntegerField()),
                ('img_owner', models.ForeignKey(default='username_missing', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
