# Generated by Django 3.1.2 on 2020-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_link_storage',
            name='twitter_img_id',
            field=models.BigIntegerField(default=123),
            preserve_default=False,
        ),
    ]
