# Generated by Django 3.1.2 on 2020-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_storage', '0002_img_link_storage_twitter_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_link_storage',
            name='img_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='img_link_storage',
            name='twitter_img_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
