# Generated by Django 3.1.2 on 2020-10-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_storage', '0003_auto_20201017_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img_link_storage',
            old_name='img_owner',
            new_name='media_owner',
        ),
        migrations.RenameField(
            model_name='img_link_storage',
            old_name='img_url',
            new_name='media_url',
        ),
        migrations.RenameField(
            model_name='img_link_storage',
            old_name='twitter_img_id',
            new_name='twitter_media_id',
        ),
    ]
