# Generated by Django 3.1.2 on 2020-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_storage', '0006_auto_20201102_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_link_storage',
            name='media_type',
            field=models.CharField(max_length=5),
        ),
    ]
