# Generated by Django 3.1.2 on 2020-11-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_storage', '0007_auto_20201102_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_link_storage',
            name='vid_length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
