# Generated by Django 3.1.2 on 2020-11-03 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_storage', '0008_img_link_storage_vid_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_link_storage',
            name='media_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
